version: "3.9"
services:
  ticketswappie:
    build: .
    image: ticketswappie
    depends_on:
      - selenium-chrome
    container_name: ticketswappie
    env_file: settings.env
  selenium-chrome:
    image: "selenium/standalone-chrome"
    shm_size: "2gb"
    expose:
      - 4444
    container_name: selenium-chrome
